# Run with: docker compose up -d
---
services:
  discord-bot:
    image: ghcr.io/cyberops7/discord-bot:test
    container_name: bot-test
    environment:  # Read env vars from .env file
      BOT_TOKEN: "${BOT_TOKEN:-}"
      LOG_DIR: "${LOG_DIR:-log}"
      LOG_FILE: "${LOG_FILE:-bot.log}"
      LOG_LEVEL_FILE: "${LOG_LEVEL_FILE:-DEBUG}"
      LOG_LEVEL_STDOUT: "${LOG_LEVEL_STDOUT:-INFO}"
    restart: unless-stopped
    volumes:
      - ./log:/app/${LOG_DIR}
