---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - discordbot.yaml
patches:
  - target:
      group: onepassword.com
      version: v1
      kind: OnePasswordItem
      name: bot-secrets
    patch: |-
     - op: replace
       path: /spec/itemPath
       value: <<< YOUR_VAULT_PATH_HERE >>>
